### ISSUE TITLE
Create a Template for Meetup Event

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#24]
# Create a Template for Meetup Event

## User Story

As a member of the organizing team of Orlando DevOps Meetup Group, I would like to have a template created for Events so that we can easily create tasks for upcoming events.

## Tasks

- [x] Create a Template
- [ ] Tell Event Creators that you created the template

## Extra Notes

> NOTE: Use one of the existing Meetups as an example

**Comment by snohio** [comment]
Here is the direct link to the [Meetup Event Template]( https://github.com/snohio/devopsorlando/issues/new?assignees=&labels=Meetup+Event&projects=&template=meetup.md&title=MONTH%2C+DAY%2C+YEAR+-+Meetup+Event+TYPE)

It also can be found by creating a new Issue in this Repo and selecting **Meetup Event Template**

**Comment by mbuchoff** [comment]
@snohio, can you add a note into the template about planning food? Since I don't have a _Settings_ button next to _Insights_, I don't think I have privileges to go into the template and add it myself.

![image](https://github.com/snohio/devopsorlando/assets/13501758/9ad0e136-a0a4-43e8-9cd6-8b9ce734be13)

**Comment by snohio** [comment]
I will, but you can update and edit. It is just a .md file here: https://github.com/snohio/devopsorlando/blob/main/.github/ISSUE_TEMPLATE/monthly-meeting-agenda.md
